// Code generated by the C-04 transport scaffold; DO NOT EDIT.
package transport

import (
	"context"

	"errors"
	api "github.com/guilycst/mastarr/internal/api/generated"
)

var errRouteUnavailable = errors.New("route service is unavailable")

type strictFallback struct{}

func (strictFallback) ListActionPlans(ctx context.Context, request api.ListActionPlansRequestObject) (api.ListActionPlansResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateActionPlan(ctx context.Context, request api.CreateActionPlanRequestObject) (api.CreateActionPlanResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetActionPlan(ctx context.Context, request api.GetActionPlanRequestObject) (api.GetActionPlanResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateActionPlanRevision(ctx context.Context, request api.CreateActionPlanRevisionRequestObject) (api.CreateActionPlanRevisionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListActionRuns(ctx context.Context, request api.ListActionRunsRequestObject) (api.ListActionRunsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetActionRun(ctx context.Context, request api.GetActionRunRequestObject) (api.GetActionRunResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListActionAttempts(ctx context.Context, request api.ListActionAttemptsRequestObject) (api.ListActionAttemptsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CancelActionRun(ctx context.Context, request api.CancelActionRunRequestObject) (api.CancelActionRunResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) RequestActionReconciliation(ctx context.Context, request api.RequestActionReconciliationRequestObject) (api.RequestActionReconciliationResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) RequestActionRetry(ctx context.Context, request api.RequestActionRetryRequestObject) (api.RequestActionRetryResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListAuditEvents(ctx context.Context, request api.ListAuditEventsRequestObject) (api.ListAuditEventsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetConfiguration(ctx context.Context, request api.GetConfigurationRequestObject) (api.GetConfigurationResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListConnectionChecks(ctx context.Context, request api.ListConnectionChecksRequestObject) (api.ListConnectionChecksResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateConnectionCheck(ctx context.Context, request api.CreateConnectionCheckRequestObject) (api.CreateConnectionCheckResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetConnectionCheck(ctx context.Context, request api.GetConnectionCheckRequestObject) (api.GetConnectionCheckResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListConnections(ctx context.Context, request api.ListConnectionsRequestObject) (api.ListConnectionsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateConnection(ctx context.Context, request api.CreateConnectionRequestObject) (api.CreateConnectionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) RetireConnection(ctx context.Context, request api.RetireConnectionRequestObject) (api.RetireConnectionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetConnection(ctx context.Context, request api.GetConnectionRequestObject) (api.GetConnectionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) PatchConnection(ctx context.Context, request api.PatchConnectionRequestObject) (api.PatchConnectionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetConnectionOptions(ctx context.Context, request api.GetConnectionOptionsRequestObject) (api.GetConnectionOptionsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListDescriptors(ctx context.Context, request api.ListDescriptorsRequestObject) (api.ListDescriptorsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetDescriptor(ctx context.Context, request api.GetDescriptorRequestObject) (api.GetDescriptorResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetDescriptorContent(ctx context.Context, request api.GetDescriptorContentRequestObject) (api.GetDescriptorContentResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListDiscoveries(ctx context.Context, request api.ListDiscoveriesRequestObject) (api.ListDiscoveriesResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetDiscovery(ctx context.Context, request api.GetDiscoveryRequestObject) (api.GetDiscoveryResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListDownloads(ctx context.Context, request api.ListDownloadsRequestObject) (api.ListDownloadsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetDownload(ctx context.Context, request api.GetDownloadRequestObject) (api.GetDownloadResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListMedia(ctx context.Context, request api.ListMediaRequestObject) (api.ListMediaResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetMedia(ctx context.Context, request api.GetMediaRequestObject) (api.GetMediaResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListMetadataCandidates(ctx context.Context, request api.ListMetadataCandidatesRequestObject) (api.ListMetadataCandidatesResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListPathMappings(ctx context.Context, request api.ListPathMappingsRequestObject) (api.ListPathMappingsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreatePathMapping(ctx context.Context, request api.CreatePathMappingRequestObject) (api.CreatePathMappingResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) RetirePathMapping(ctx context.Context, request api.RetirePathMappingRequestObject) (api.RetirePathMappingResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetPathMapping(ctx context.Context, request api.GetPathMappingRequestObject) (api.GetPathMappingResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) PatchPathMapping(ctx context.Context, request api.PatchPathMappingRequestObject) (api.PatchPathMappingResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateReviewDecision(ctx context.Context, request api.CreateReviewDecisionRequestObject) (api.CreateReviewDecisionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetReviewDecision(ctx context.Context, request api.GetReviewDecisionRequestObject) (api.GetReviewDecisionResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListScans(ctx context.Context, request api.ListScansRequestObject) (api.ListScansResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateScan(ctx context.Context, request api.CreateScanRequestObject) (api.CreateScanResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetScan(ctx context.Context, request api.GetScanRequestObject) (api.GetScanResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CancelScan(ctx context.Context, request api.CancelScanRequestObject) (api.CancelScanResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListStorageRoots(ctx context.Context, request api.ListStorageRootsRequestObject) (api.ListStorageRootsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateStorageRoot(ctx context.Context, request api.CreateStorageRootRequestObject) (api.CreateStorageRootResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) RetireStorageRoot(ctx context.Context, request api.RetireStorageRootRequestObject) (api.RetireStorageRootResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetStorageRoot(ctx context.Context, request api.GetStorageRootRequestObject) (api.GetStorageRootResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) PatchStorageRoot(ctx context.Context, request api.PatchStorageRootRequestObject) (api.PatchStorageRootResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListTrash(ctx context.Context, request api.ListTrashRequestObject) (api.ListTrashResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetTrash(ctx context.Context, request api.GetTrashRequestObject) (api.GetTrashResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) ListWorkflowRuns(ctx context.Context, request api.ListWorkflowRunsRequestObject) (api.ListWorkflowRunsResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CreateWorkflowRun(ctx context.Context, request api.CreateWorkflowRunRequestObject) (api.CreateWorkflowRunResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetWorkflowRun(ctx context.Context, request api.GetWorkflowRunRequestObject) (api.GetWorkflowRunResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) CancelWorkflowRun(ctx context.Context, request api.CancelWorkflowRunRequestObject) (api.CancelWorkflowRunResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetLiveHealth(ctx context.Context, request api.GetLiveHealthRequestObject) (api.GetLiveHealthResponseObject, error) {
	return nil, errRouteUnavailable
}

func (strictFallback) GetReadyHealth(ctx context.Context, request api.GetReadyHealthRequestObject) (api.GetReadyHealthResponseObject, error) {
	return nil, errRouteUnavailable
}
